spring:
  profiles:
    active: unkonw

---
spring:
  profiles: 
    active: dev
  application:
    name: microservice-config-dev

---
spring:
  profiles: 
    active: test
  application:
    name: microservice-config-test