spring:
  profiles:
    active: dev
    
---
server:
  port: 3355
  
spring:
  profiles: dev
  application:
    name: microservice-config-client-3355

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


test:
  words: abcd

      
---
server:
  port: 3356
  
spring:
  profiles: test
  application:
    name: microservice-config-client-3356

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/