spring:
  profiles:
    active: dev
    
---
server: 
  port: 8201
spring:
  profiles: dev
  application:
    name: microservice-config-client-8201

eureka:
  client:
    service-url:
    defaultZone: http://127.0.0.1/7001/eureka    